#!/usr/bin/php -q
<?php

$root = getcwd();

$files = scandir($root);
$isXcodeProj = false;
foreach ($files as $file) {
    echo $file;
    if (strpos($file,'.xcodeproj') !== false) {
        $isXcodeProj = true;
    }
}

if ($isXcodeProj) {
    echo "isXcodeProj = true", "\n";
}
else {
    die("[Error] Not a valid xcode project directory!"."\n");
}

scanInterfaceBuilderFiles($root);

function scanInterfaceBuilderFiles($dir) {
    $files = scandir($dir);
    foreach ($files as $file) {
        if ($file == '.' || $file == '..' || $file == 'Pods') {
            continue;
        }
        else if (is_dir($dir.'/'.$file)) {
            scanInterfaceBuilderFiles($dir.'/'.$file);
        }
        else {
            if (strpos($file, '.storyboard') !== false || strpos($file, '.xib') !== false) {
                $changed = replaceColorSpace($dir.'/'.$file);
                echo 'file = ', $file, " " ,($changed ? "[Change]" : "[OK]"), "\n";
            }
        }
    }
}

function replaceColorSpace($filePath) {
    ///舊的Red
    $oldRedColor = "0.8431";
    ///舊的Green
    $oldGreenColor = "0.2156";
    ///舊的Blue
    $oldBlueColor = "0.2588";
    ///舊的Alpha
    $oldAlpha = "1";
    ///新的Red
    $newRedColor = "1";
    ///新的Green
    $newGreenColor = "1";
    ///新的Blue
    $newBlueColor = "0";
    ///新的Alpha
    $newAlpha = "1";

    $fileContents = file_get_contents($filePath);
    $redPattern = '/red="'.$oldRedColor.'[0-9]+"/';
    $greenPattern = '/green="'.$oldGreenColor.'[0-9]+"/';
    $bluePattern = '/blue="'.$oldBlueColor.'[0-9]+"/';
    $alphaPattern = '/alpha="'.$oldAlpha.'[0-9]+"/';
    $fileContents = preg_replace($redPattern, 'red="'.$oldRedColor.'"', $fileContents);
    $fileContents = preg_replace($greenPattern, 'green="'.$oldGreenColor.'"', $fileContents);
    $fileContents = preg_replace($bluePattern, 'blue="'.$oldBlueColor.'"', $fileContents);
    $fileContents = preg_replace($alphaPattern, 'alpha="'.$oldAlpha.'"', $fileContents);
    $oldColor = 'red="'.$oldRedColor.'" green="'.$oldGreenColor.'" blue="'.$oldBlueColor.'" alpha="'.$oldAlpha.'"';
    $newColor = 'red="'.$newRedColor.'" green="'.$newGreenColor.'" blue="'.$newBlueColor.'" alpha="'.$newAlpha.'"';
    $replaceContents = str_replace($oldColor, $newColor, $fileContents);
        
    if($replaceContents == $fileContents) {
        return false;
    }
    else {
        file_put_contents($filePath, $replaceContents);
        return true;
    }
}
